const countries = [
  'United States of America',
  'China',
  'India',
  'Indonesia',
  'Pakistan',
  'Brazil',
  'Nigeria',
  'Bangladesh',
  'Russia',
  'Mexico',
  'Japan',
  'Ethiopia',
  'Philippines',
  'Egypt',
  'Vietnam',
  'DR Congo',
  'Turkey',
  'Iran',
  'Germany',
  'Thailand',
  'United Kingdom',
  'France',
  'Italy',
  'Tanzania',
  'South Africa',
  'Myanmar',
  'South Korea',
  'Colombia',
  'Kenya',
  'Spain',
  'Ukraine',
  'Uganda',
  'Argentina',
  'Algeria',
  'Sudan',
  'Iraq',
  'Poland',
  'Canada',
  'Morocco',
  'Afghanistan',
  'Saudi Arabia',
  'Uzbekistan',
  'Peru',
  'Malaysia',
  'Mozambique',
  'Nepal',
  'Venezuela',
  'Yemen',
  'Ghana',
  'Mali',
  'Madagascar',
  'Cameroon',
  "Côte d'Ivoire",
  'North Korea',
  'Australia',
  'Niger',
  'Taiwan',
  'Sri Lanka',
  'Burkina Faso',
  'Mali',
  'Syria',
  'Romania',
  'Kazakhstan',
  'Netherlands',
  'Chad',
  'Somalia',
  'Zambia',
  'Zimbabwe',
  'Guinea',
  'Rwanda',
  'Benin',
  'Burundi',
  'Tunisia',
  'Bolivia',
  'Belgium',
  'Haiti',
  'Cuba',
  'South Sudan',
  'Dominican Republic',
  'Czech Republic (Czechia)',
  'Greece',
  'Jordan',
  'Portugal',
  'Azerbaijan',
  'Sweden',
  'United Arab Emirates',
  'Honduras',
  'Hungary',
  'Tajikistan',
  'Belarus',
  'Austria',
  'Papua New Guinea',
  'Serbia',
  'Switzerland',
  'Israel',
  'Sierra Leone',
];

export default countries.sort((a, b) => a.localeCompare(b));
