import IProduct from '../models/products';

const productDB: IProduct[] = [
  {
    id: '1',
    name: 'iPhone 14 Pro Max',
    category: 'smartphones',
    brand: 'apple',
    release: '2022',
    color: 'Deep Purple',
    model: '(MQC53)',
    price: '1,599',
    storage: '1Tb',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-deep-purple-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-deep-purple-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-deep-purple-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-deep-purple-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-deep-purple-5.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-deep-purple-6.jpg',
    ],
    rating: 5,
    stock: 101,
    displaySize: `6.7”`,
    display: 'Super Retina XDR',
    resolution: '2778 x 1284',
    ppi: '458ppi',
    refreshRate: '120Hz',
    communication: 'GPS; Wi-Fi; Bluetooth; Lightning',
    features:
      'wireless charging; face ID; quick charge; LiDAR, emergency SOS via satellite',
    batteryType: 'Li-Ion',
    sdCardSupport: 'no',
    internet: '3G; 5G; 4G (LTE)',
    numOfSIMs: '1 + eSIM',
    typeOfSIM: 'Nano-SIM; eSIM',
    chipset: 'Apple A16 Bionic',
    cameras: '48MP + 12MP + 12MP + 12MP',
    maxVideoRecording: '2160p@60fps',
    bluetooth: '5.3',
    nfc: 'yes',
    os: 'iOS',
    osVersion: '16',
    protection: 'IP68',
    material: 'glass',
    size: '160.7 x 77.6 x 7.85mm',
    weight: '255g',
  },
  {
    id: '2',
    name: 'iPhone 14 Pro Max',
    category: 'smartphones',
    brand: 'apple',
    release: '2022',
    color: 'Gold',
    model: '(MQ9W3)',
    price: '1,199',
    storage: '256Gb',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-gold-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-gold-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-gold-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-gold-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-gold-5.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro-max/iphone-14-pro-max-gold-6.jpg',
    ],
    rating: 5,
    stock: 219,
    displaySize: `6.7”`,
    display: 'Super Retina XDR',
    resolution: '2778 x 1284',
    ppi: '458ppi',
    refreshRate: '120Hz',
    communication: 'GPS; Wi-Fi; Bluetooth; Lightning',
    features:
      'wireless charging; face ID; quick charge; LiDAR, emergency SOS via satellite',
    batteryType: 'Li-Ion',
    sdCardSupport: 'no',
    internet: '3G; 5G; 4G (LTE)',
    numOfSIMs: '1 + eSIM',
    typeOfSIM: 'Nano-SIM; eSIM',
    chipset: 'Apple A16 Bionic',
    cameras: '48MP + 12MP + 12MP + 12MP',
    maxVideoRecording: '2160p@60fps',
    bluetooth: '5.3',
    nfc: 'yes',
    os: 'iOS',
    osVersion: '16',
    protection: 'IP68',
    material: 'glass',
    size: '160.7 x 77.6 x 7.85mm',
    weight: '255g',
  },
  {
    id: '3',
    name: 'iPhone 14 Pro',
    category: 'smartphones',
    brand: 'apple',
    release: '2022',
    color: 'Silver',
    model: '(MQ1W3)',
    price: '1,299',
    storage: '512Gb',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-silver-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-silver-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-silver-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-silver-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-silver-5.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-silver-6.jpg',
    ],
    rating: 5,
    stock: 56,
    displaySize: `6.1”`,
    display: 'Super Retina XDR',
    resolution: '2532 x 1170',
    ppi: '460ppi',
    refreshRate: '120Hz',
    communication: 'GPS; Wi-Fi; Bluetooth; Lightning',
    features:
      'wireless charging; face ID; quick charge; LiDAR, emergency SOS via satellite',
    batteryType: 'Li-Ion',
    sdCardSupport: 'no',
    internet: '3G; 5G; 4G (LTE)',
    numOfSIMs: '1 + eSIM',
    typeOfSIM: 'Nano-SIM; eSIM',
    chipset: 'Apple A16 Bionic',
    cameras: '48MP + 12MP + 12MP + 12MP',
    maxVideoRecording: '2160p@60fps',
    bluetooth: '5.3',
    nfc: 'yes',
    os: 'iOS',
    osVersion: '16',
    protection: 'IP68',
    material: 'glass',
    size: '147.5 x 71.5 x 7.85mm',
    weight: '215g',
  },
  {
    id: '4',
    name: 'iPhone 14 Pro',
    category: 'smartphones',
    brand: 'apple',
    release: '2022',
    color: 'Space Black',
    model: '(MPXV3)',
    price: '999',
    storage: '128Gb',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-space-black-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-space-black-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-space-black-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-space-black-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-space-black-5.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-pro/iphone-14-pro-space-black-6.jpg',
    ],
    rating: 5,
    stock: 182,
    displaySize: `6.1”`,
    display: 'Super Retina XDR',
    resolution: '2532 x 1170',
    ppi: '460ppi',
    refreshRate: '120Hz',
    communication: 'GPS; Wi-Fi; Bluetooth; Lightning',
    features:
      'wireless charging; face ID; quick charge; LiDAR, emergency SOS via satellite',
    batteryType: 'Li-Ion',
    sdCardSupport: 'no',
    internet: '3G; 5G; 4G (LTE)',
    numOfSIMs: '1 + eSIM',
    typeOfSIM: 'Nano-SIM; eSIM',
    chipset: 'Apple A16 Bionic',
    cameras: '48MP + 12MP + 12MP + 12MP',
    maxVideoRecording: '2160p@60fps',
    bluetooth: '5.3',
    nfc: 'yes',
    os: 'iOS',
    osVersion: '16',
    protection: 'IP68',
    material: 'glass',
    size: '147.5 x 71.5 x 7.85mm',
    weight: '215g',
  },
  {
    id: '5',
    name: 'AirPods 2nd Generation',
    category: 'headphones',
    brand: 'apple',
    release: '2019',
    color: 'White',
    model: '(MV7N2RU/A)',
    price: '129',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-2-nd-gen/airpods-2-nd-gen-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-2-nd-gen/airpods-2-nd-gen-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-2-nd-gen/airpods-2-nd-gen-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-2-nd-gen/airpods-2-nd-gen-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-2-nd-gen/airpods-2-nd-gen-5.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-2-nd-gen/airpods-2-nd-gen-6.jpg',
    ],
    rating: 4,
    stock: 36,
    bluetooth: '5.0',
    chipset: 'Apple H1',
    protection: 'no',
    earpieceDesign: 'in-ear',
    construction: 'TWS',
    connection: 'wireless',
    activeNoiseCancellation: 'no',
    numOfMics: '2',
    sensors: 'accelerometer, touch',
    audioCodec: 'AAC',
    weight: '3g (each)',
    caseWeight: '37g',
  },
  {
    id: '6',
    name: 'AirPods 3rd Generation',
    category: 'headphones',
    brand: 'apple',
    release: '2021',
    color: 'White',
    model: '(MME73TY/A)',
    price: '169',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-3rd-generation/airpods-3rd-generation-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-3rd-generation/airpods-3rd-generation-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-3rd-generation/airpods-3rd-generation-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-3rd-generation/airpods-3rd-generation-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-3rd-generation/airpods-3rd-generation-5.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-3rd-generation/airpods-3rd-generation-6.jpg',
    ],
    rating: 5,
    stock: 67,
    bluetooth: '5.0',
    chipset: 'Apple H1',
    protection: 'IPX4',
    earpieceDesign: 'in-ear',
    construction: 'TWS',
    connection: 'wireless',
    activeNoiseCancellation: 'no',
    numOfMics: '2',
    sensors: 'accelerometer, gyroscope, Touch',
    audioCodec: 'AAC',
    weight: '4.3g (each)',
    caseWeight: '37.9g',
  },
  {
    id: '7',
    name: `MacBook Pro M1 Pro`,
    category: 'laptops',
    brand: 'apple',
    release: '2021',
    color: 'Space Gray',
    model: '(MK183UA/A)',
    price: '2,499',
    storage: '512Gb',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/laptops/apple/macbook-pro-m1-pro-16/macbook-pro-m1-pro-16-space-grey-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/laptops/apple/macbook-pro-m1-pro-16/macbook-pro-m1-pro-16-space-grey-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/laptops/apple/macbook-pro-m1-pro-16/macbook-pro-m1-pro-16-space-grey-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/laptops/apple/macbook-pro-m1-pro-16/macbook-pro-m1-pro-16-space-grey-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/laptops/apple/macbook-pro-m1-pro-16/macbook-pro-m1-pro-16-space-grey-5.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/laptops/apple/macbook-pro-m1-pro-16/macbook-pro-m1-pro-16-space-grey-6.jpg',
    ],
    rating: 5,
    stock: 231,
    displaySize: `16”`,
    display: 'Liquid Retina XDR',
    coating: 'glossy',
    resolution: '3456 x 2234',
    refreshRate: '120Hz',
    communication: 'Wi-Fi; Bluetooth',
    features: 'fingerprint sensor, keyboard backlight',
    chipsetCores: '10',
    ram: '16Gb',
    storageType: 'SSD',
    graphicsCardType: 'Integrated',
    chipset: 'Apple M1 Pro',
    os: 'MacOS',
    wifiStandart: 'IEEE 802.11 ax',
    ports: 'HDMI; Thunderbolt; SD card reader; Audio jack (3.5 mm)',
    protection: 'no',
    material: 'metal',
    size: '355.7 x 248.1 x 16.8mm',
    webCamera: '1080p',
    weight: '2.1kg',
  },
  {
    id: '8',
    name: 'Watch Ultra GPS + Cellular 49mm Titanium Case/Green Alpine Loop L',
    category: 'watches',
    brand: 'apple',
    release: '2022',
    bandColor: 'Green',
    model: '(MQFP3UL/A)',
    price: '799',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-ultra-gps+cellular-49mm-titanium/apple-watch-ultra-gps+cellular-49mm-titanium-green-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-ultra-gps+cellular-49mm-titanium/apple-watch-ultra-gps+cellular-49mm-titanium-green-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-ultra-gps+cellular-49mm-titanium/apple-watch-ultra-gps+cellular-49mm-titanium-green-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-ultra-gps+cellular-49mm-titanium/apple-watch-ultra-gps+cellular-49mm-titanium-green-4.jpg',
    ],
    rating: 5,
    stock: 27,
    os: 'WatchOS',
    osVersion: '9.0',
    training: 'cycling, running, swimming',
    bodyShape: 'rectangle',
    control: 'buttons, touch screen',
    sensors:
      'accelerometer, gyro, heart rate, barometer, always-on altimeter, compass, SpO2',
    communication: 'GPS; Wi-Fi; Bluetooth',
    nfc: 'yes',
    protection: 'IP6X',
    resolution: '410 x 502',
    display: 'Retina',
    caseSize: '49mm',
    bluetooth: '5.3',
    storage: '32Gb',
    chipset: 'Apple S8',
    batteryType: 'Li-Ion',
    material: 'titan',
    size: '49 x 44 x 14.4mm',
    weight: '61.3g',
  },
  {
    id: '9',
    name: 'iPad Pro 12.9” Wi-Fi + Cellular',
    category: 'tablets',
    brand: 'apple',
    release: '2022',
    color: 'Space Gray',
    model: '(MP1X3RK/A)',
    price: '1,799',
    storage: '1Tb',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/tablets/apple/ipad-pro-12.9-wi-fi+cellular/ipad-pro-12.9-wi-fi+cellular-space-gray-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/tablets/apple/ipad-pro-12.9-wi-fi+cellular/ipad-pro-12.9-wi-fi+cellular-space-gray-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/tablets/apple/ipad-pro-12.9-wi-fi+cellular/ipad-pro-12.9-wi-fi+cellular-space-gray-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/tablets/apple/ipad-pro-12.9-wi-fi+cellular/ipad-pro-12.9-wi-fi+cellular-space-gray-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/tablets/apple/ipad-pro-12.9-wi-fi+cellular/ipad-pro-12.9-wi-fi+cellular-space-gray-5.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/tablets/apple/ipad-pro-12.9-wi-fi+cellular/ipad-pro-12.9-wi-fi+cellular-space-gray-6.jpg',
    ],
    rating: 5,
    stock: 143,
    displaySize: `12.9”`,
    display: 'Liquid Retina XDR',
    resolution: '2732 x 2048',
    ppi: '264ppi',
    refreshRate: '120Hz',
    chipsetCores: '8',
    ram: '8Gb',
    communication: 'GPS; Wi-Fi; Bluetooth',
    features: 'dual camera; face ID',
    ports: 'USB Type-C',
    sdCardSupport: 'no',
    internet: '2G 3G; 5G; 4G (LTE)',
    numOfSIMs: '1 + eSIM',
    typeOfSIM: 'Nano-SIM; eSIM',
    chipset: 'Apple M2',
    cameras: '12MP + 10MP + 12MP',
    maxVideoRecording: '2160p@60fps',
    bluetooth: '5.3',
    os: 'iPadOS',
    osVersion: '16',
    protection: 'no',
    material: 'aluminum',
    size: '280.6 x 214.9 x 6.4mm',
    weight: '685g',
  },
  {
    id: '10',
    name: 'iPhone 14 Plus',
    category: 'smartphones',
    brand: 'apple',
    release: '2022',
    color: 'Blue',
    model: '(MQ523)',
    price: '899',
    storage: '128Gb',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-plus/iphone-14-plus-blue-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-plus/iphone-14-plus-blue-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-plus/iphone-14-plus-blue-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-plus/iphone-14-plus-blue-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-plus/iphone-14-plus-blue-5.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-plus/iphone-14-plus-blue-6.jpg',
    ],
    rating: 4,
    stock: 282,
    displaySize: `6.7”`,
    display: 'Super Retina XDR',
    resolution: '2778 x 1284',
    ppi: '458ppi',
    refreshRate: '120Hz',
    communication: 'GPS; Wi-Fi; Bluetooth; Lightning',
    features:
      'wireless charging; face ID; quick charge; emergency SOS via satellite',
    batteryType: 'Li-Ion',
    sdCardSupport: 'no',
    internet: '3G; 5G; 4G (LTE)',
    numOfSIMs: '1 + eSIM',
    typeOfSIM: 'Nano-SIM; eSIM',
    chipset: 'Apple A15 Bionic',
    cameras: '12MP + 12MP + 12MP',
    maxVideoRecording: '2160p@60fps',
    bluetooth: '5.3',
    nfc: 'yes',
    os: 'iOS',
    osVersion: '16',
    protection: 'IP68',
    material: 'glass',
    size: '160.8 x 78.1 x 7.8mm',
    weight: '245g',
  },
  {
    id: '11',
    name: 'iPhone 14 Plus',
    category: 'smartphones',
    brand: 'apple',
    release: '2022',
    color: 'Midnight',
    model: '(MQ533)',
    price: '999',
    storage: '256Gb',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-plus/iphone-14-plus-midnight-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-plus/iphone-14-plus-midnight-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-plus/iphone-14-plus-midnight-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-plus/iphone-14-plus-midnight-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-plus/iphone-14-plus-midnight-5.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14-plus/iphone-14-plus-midnight-6.jpg',
    ],
    rating: 4,
    stock: 165,
    displaySize: `6.7”`,
    display: 'Super Retina XDR',
    resolution: '2778 x 1284',
    ppi: '458ppi',
    refreshRate: '120Hz',
    communication: 'GPS; Wi-Fi; Bluetooth; Lightning',
    features:
      'wireless charging; face ID; quick charge; emergency SOS via satellite',
    batteryType: 'Li-Ion',
    sdCardSupport: 'no',
    internet: '3G; 5G; 4G (LTE)',
    numOfSIMs: '1 + eSIM',
    typeOfSIM: 'Nano-SIM; eSIM',
    chipset: 'Apple A15 Bionic',
    cameras: '12MP + 12MP + 12MP',
    maxVideoRecording: '2160p@60fps',
    bluetooth: '5.3',
    nfc: 'yes',
    os: 'iOS',
    osVersion: '16',
    protection: 'IP68',
    material: 'glass',
    size: '160.8 x 78.1 x 7.8mm',
    weight: '245g',
  },
  {
    id: '12',
    name: 'iPhone 14',
    category: 'smartphones',
    brand: 'apple',
    release: '2022',
    color: 'Purple',
    model: '(MPX93)',
    price: '1,199',
    storage: '512Gb',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14/iphone-14-purple-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14/iphone-14-purple-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14/iphone-14-purple-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14/iphone-14-purple-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14/iphone-14-purple-5.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14/iphone-14-purple-6.jpg',
    ],
    rating: 5,
    stock: 59,
    displaySize: `6.1”`,
    display: 'Super Retina XDR',
    resolution: '2532 x 1170',
    ppi: '460ppi',
    refreshRate: '60Hz',
    communication: 'GPS; Lightning; NFC; Wi-Fi; Bluetooth',
    features:
      'wireless charging; face ID; quick charge; emergency SOS via satellite',
    batteryType: 'Li-Ion',
    sdCardSupport: 'no',
    internet: '3G; 5G; 4G (LTE)',
    numOfSIMs: '1 + eSIM',
    typeOfSIM: 'Nano-SIM; eSIM',
    chipset: 'Apple A15 Bionic',
    cameras: '12MP + 12MP + 12MP',
    maxVideoRecording: '2160p@60fps',
    bluetooth: '5.3',
    nfc: 'yes',
    os: 'iOS',
    osVersion: '16',
    protection: 'IP68',
    material: 'glass',
    size: '146.7 x 71.5 x 7.8mm',
    weight: '173g',
  },
  {
    id: '13',
    name: 'iPhone 14',
    category: 'smartphones',
    brand: 'apple',
    release: '2022',
    color: 'PRODUCT Red',
    model: '(MPVA3)',
    price: '799',
    storage: '128Gb',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14/iphone-14-product-red-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14/iphone-14-product-red-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14/iphone-14-product-red-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14/iphone-14-product-red-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14/iphone-14-product-red-5.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14/iphone-14-product-red-6.jpg',
    ],
    rating: 5,
    stock: 61,
    displaySize: `6.1”`,
    display: 'Super Retina XDR',
    resolution: '2532 x 1170',
    ppi: '460ppi',
    refreshRate: '60Hz',
    communication: 'GPS; Lightning; NFC; Wi-Fi; Bluetooth',
    features:
      'wireless charging; face ID; quick charge; emergency SOS via satellite',
    batteryType: 'Li-Ion',
    sdCardSupport: 'no',
    internet: '3G; 5G; 4G (LTE)',
    numOfSIMs: '1 + eSIM',
    typeOfSIM: 'Nano-SIM; eSIM',
    chipset: 'Apple A15 Bionic',
    cameras: '12MP + 12MP + 12MP',
    maxVideoRecording: '2160p@60fps',
    bluetooth: '5.3',
    nfc: 'yes',
    os: 'iOS',
    osVersion: '16',
    protection: 'IP68',
    material: 'glass',
    size: '146.7 x 71.5 x 7.8mm',
    weight: '173g',
  },
  {
    id: '14',
    name: 'iPhone 14',
    category: 'smartphones',
    brand: 'apple',
    release: '2022',
    color: 'Starlight',
    model: '(MPW43)',
    price: '899',
    storage: '256Gb',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14/iphone-14-starlight-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14/iphone-14-starlight-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14/iphone-14-starlight-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14/iphone-14-starlight-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14/iphone-14-starlight-5.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/smartphones/apple/iphone-14/iphone-14-starlight-6.jpg',
    ],
    rating: 5,
    stock: 29,
    displaySize: `6.1”`,
    display: 'Super Retina XDR',
    resolution: '2532 x 1170',
    ppi: '460ppi',
    refreshRate: '60Hz',
    communication: 'GPS; Lightning; NFC; Wi-Fi; Bluetooth',
    features:
      'wireless charging; face ID; quick charge; emergency SOS via satellite',
    batteryType: 'Li-Ion',
    sdCardSupport: 'no',
    internet: '3G; 5G; 4G (LTE)',
    numOfSIMs: '1 + eSIM',
    typeOfSIM: 'Nano-SIM; eSIM',
    chipset: 'Apple A15 Bionic',
    cameras: '12MP + 12MP + 12MP',
    maxVideoRecording: '2160p@60fps',
    bluetooth: '5.3',
    nfc: 'yes',
    os: 'iOS',
    osVersion: '16',
    protection: 'IP68',
    material: 'glass',
    size: '146.7 x 71.5 x 7.8mm',
    weight: '173g',
  },
  {
    id: '15',
    name: 'AirPods Pro 2nd Generation',
    category: 'headphones',
    brand: 'apple',
    release: '2022',
    color: 'White',
    model: '(MQD83TY/A)',
    price: '249',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-pro-2nd-generation/airpods-pro-2nd-generation-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-pro-2nd-generation/airpods-pro-2nd-generation-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-pro-2nd-generation/airpods-pro-2nd-generation-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-pro-2nd-generation/airpods-pro-2nd-generation-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-pro-2nd-generation/airpods-pro-2nd-generation-5.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-pro-2nd-generation/airpods-pro-2nd-generation-6.jpg',
    ],
    rating: 5,
    stock: 67,
    bluetooth: '5.3',
    chipset: 'Apple H2',
    protection: 'IPX4',
    earpieceDesign: 'in-ear',
    construction: 'TWS',
    connection: 'wireless',
    activeNoiseCancellation: 'yes',
    numOfMics: '3',
    sensors: 'accelerometer, touch',
    audioCodec: 'AAC',
    weight: '5.3g (each)',
    caseWeight: '50.8g',
  },
  {
    id: '16',
    name: 'AirPods Max Green',
    category: 'headphones',
    brand: 'apple',
    release: '2020',
    color: 'Green',
    model: '(MGYN3RU/A)',
    price: '549',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-max/airpods-max-green-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-max/airpods-max-green-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-max/airpods-max-green-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-max/airpods-max-green-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-max/airpods-max-green-5.jpg',
    ],
    rating: 5,
    stock: 16,
    bluetooth: '5.0',
    chipset: 'Apple H2',
    protection: 'IPX4',
    earpieceDesign: 'over-ear',
    construction: 'TWS',
    connection: 'wireless',
    activeNoiseCancellation: 'yes',
    numOfMics: '3',
    sensors: 'accelerometer, gyroscope, proximity',
    audioCodec: 'AAC',
    weight: '384.8g',
    caseWeight: '134.5g',
  },
  {
    id: '17',
    name: 'AirPods Max Space Gray',
    category: 'headphones',
    brand: 'apple',
    release: '2020',
    color: 'Space Gray',
    model: '(MGYH3RU/A)',
    price: '549',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-max/airpods-max-space-gray-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-max/airpods-max-space-gray-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-max/airpods-max-space-gray-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-max/airpods-max-space-gray-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/headphones/apple/airpods-max/airpods-max-space-gray-5.jpg',
    ],
    rating: 5,
    stock: 10,
    bluetooth: '5.0',
    chipset: 'Apple H2',
    protection: 'IPX4',
    earpieceDesign: 'over-ear',
    construction: 'TWS',
    connection: 'wireless',
    activeNoiseCancellation: 'yes',
    numOfMics: '3',
    sensors: 'accelerometer, gyroscope, proximity',
    audioCodec: 'AAC',
    weight: '384.8g',
    caseWeight: '134.5g',
  },
  {
    id: '18',
    name: `MacBook Pro M2`,
    category: 'laptops',
    brand: 'apple',
    release: '2022',
    color: 'Silver',
    model: '(MNEP3)',
    price: '1,299',
    storage: '256Gb',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/laptops/apple/macbook-pro-m2-13.3/macbook-pro-m2-13.3-silver-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/laptops/apple/macbook-pro-m2-13.3/macbook-pro-m2-13.3-silver-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/laptops/apple/macbook-pro-m2-13.3/macbook-pro-m2-13.3-silver-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/laptops/apple/macbook-pro-m2-13.3/macbook-pro-m2-13.3-silver-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/laptops/apple/macbook-pro-m2-13.3/macbook-pro-m2-13.3-silver-5.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/laptops/apple/macbook-pro-m2-13.3/macbook-pro-m2-13.3-silver-6.jpg',
    ],
    rating: 5,
    stock: 111,
    displaySize: `13.3”`,
    display: 'Retina',
    coating: 'glossy',
    resolution: '2560 x 1600',
    refreshRate: '60Hz',
    communication: 'Wi-Fi; Bluetooth',
    features: 'fingerprint sensor, keyboard backlight',
    chipsetCores: '8',
    ram: '8Gb',
    storageType: 'SSD',
    graphicsCardType: 'Integrated',
    chipset: 'Apple M2',
    os: 'MacOS',
    wifiStandart: 'IEEE 802.11 ax',
    ports: 'Thunderbolt; Audio jack (3.5 mm)',
    protection: 'no',
    material: 'plastic',
    size: '304.1 x 212.4 x 15.6mm',
    webCamera: '720p',
    weight: '1.4kg',
  },
  {
    id: '19',
    name: `MacBook Air M2`,
    category: 'laptops',
    brand: 'apple',
    release: '2022',
    color: 'Midnight',
    model: '(MLY33UA/A)',
    price: '1,499',
    storage: '512Gb',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/laptops/apple/macbook-air-m2-13.6/macbook-air-m2-13.6-midnight-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/laptops/apple/macbook-air-m2-13.6/macbook-air-m2-13.6-midnight-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/laptops/apple/macbook-air-m2-13.6/macbook-air-m2-13.6-midnight-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/laptops/apple/macbook-air-m2-13.6/macbook-air-m2-13.6-midnight-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/laptops/apple/macbook-air-m2-13.6/macbook-air-m2-13.6-midnight-5.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/laptops/apple/macbook-air-m2-13.6/macbook-air-m2-13.6-midnight-6.jpg',
    ],
    rating: 5,
    stock: 42,
    displaySize: `13.6”`,
    display: 'Liquid Retina',
    coating: 'anti-reflective',
    resolution: '2560 x 1664',
    refreshRate: '60Hz',
    communication: 'Wi-Fi; Bluetooth',
    features: 'fingerprint sensor, keyboard backlight',
    chipsetCores: '8',
    ram: '8Gb',
    storageType: 'SSD',
    graphicsCardType: 'Integrated',
    chipset: 'Apple M2',
    os: 'MacOS',
    wifiStandart: 'IEEE 802.11 a/b/g/n/ac/ax',
    ports: 'Thunderbolt; Audio jack (3.5 mm)',
    protection: 'no',
    material: 'aluminum',
    size: '304.1 x 215 x 11.3mm',
    webCamera: '1080p',
    weight: '1.24kg',
  },
  {
    id: '20',
    name: 'Watch Ultra GPS + Cellular, 49mm Titanium Case/White Ocean Band',
    category: 'watches',
    brand: 'apple',
    release: '2022',
    bandColor: 'White',
    model: '(MNHF3UL/A)',
    price: '799',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-ultra-gps+cellular-49mm-titanium/apple-watch-ultra-gps+cellular-49mm-titanium-starlight-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-ultra-gps+cellular-49mm-titanium/apple-watch-ultra-gps+cellular-49mm-titanium-starlight-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-ultra-gps+cellular-49mm-titanium/apple-watch-ultra-gps+cellular-49mm-titanium-starlight-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-ultra-gps+cellular-49mm-titanium/apple-watch-ultra-gps+cellular-49mm-titanium-starlight-4.jpg',
    ],
    rating: 5,
    stock: 15,
    os: 'WatchOS',
    osVersion: '9.0',
    training: 'cycling, running, swimming',
    bodyShape: 'rectangle',
    control: 'buttons, touch screen',
    sensors:
      'accelerometer, gyro, heart rate, barometer, always-on altimeter, compass, SpO2',
    communication: 'GPS; Wi-Fi; Bluetooth',
    nfc: 'yes',
    protection: 'IP6X',
    resolution: '410 x 502',
    display: 'Retina',
    caseSize: '49mm',
    bluetooth: '5.3',
    storage: '32Gb',
    chipset: 'Apple S8',
    batteryType: 'Li-Ion',
    material: 'titan',
    size: '49 x 44 x 14.4mm',
    weight: '61.3g',
  },
  {
    id: '21',
    name: 'Watch S8 GPS 41mm Midnight Aluminium Midnight Sp/B',
    category: 'watches',
    brand: 'apple',
    release: '2022',
    bandColor: 'Midnight',
    model: '(MNP53UL/A)',
    price: '399',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-s8-gps-41/apple-watch-s8-gps-41-midnight-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-s8-gps-41/apple-watch-s8-gps-41-midnight-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-s8-gps-41/apple-watch-s8-gps-41-midnight-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-s8-gps-41/apple-watch-s8-gps-41-midnight-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-s8-gps-41/apple-watch-s8-gps-41-midnight-5.jpg',
    ],
    rating: 5,
    stock: 15,
    os: 'WatchOS',
    osVersion: '9.0',
    training: 'cycling, running, swimming',
    bodyShape: 'rectangle',
    control: 'buttons, touch screen',
    sensors:
      'accelerometer, gyro, heart rate, barometer, always-on altimeter, compass, SpO2',
    communication: 'GPS; Wi-Fi; Bluetooth',
    nfc: 'yes',
    protection: 'IP6X',
    resolution: '352 x 430',
    display: 'Retina',
    caseSize: '41mm',
    bluetooth: '5.0',
    storage: '32Gb',
    chipset: 'Apple S8',
    batteryType: 'Li-Ion',
    material: 'aluminium',
    size: '41 x 35 x 10.7mm',
    weight: '42.3g',
  },
  {
    id: '22',
    name: 'Watch S8 GPS 45mm Silver Aluminium White Sp/B',
    category: 'watches',
    brand: 'apple',
    release: '2022',
    bandColor: 'White',
    model: '(MP6N3UL/A)',
    price: '429',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-s8-gps-45/apple-watch-s8-gps-45-silver-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-s8-gps-45/apple-watch-s8-gps-45-silver-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-s8-gps-45/apple-watch-s8-gps-45-silver-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-s8-gps-45/apple-watch-s8-gps-45-silver-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-s8-gps-45/apple-watch-s8-gps-45-silver-5.jpg',
    ],
    rating: 5,
    stock: 21,
    os: 'WatchOS',
    osVersion: '9.0',
    training: 'cycling, running, swimming',
    bodyShape: 'rectangle',
    control: 'buttons, touch screen',
    sensors:
      'accelerometer, gyro, heart rate, barometer, always-on altimeter, compass, SpO2',
    communication: 'GPS; Wi-Fi; Bluetooth',
    nfc: 'yes',
    protection: 'IP6X',
    resolution: '352 x 430',
    display: 'Retina',
    caseSize: '45mm',
    bluetooth: '5.0',
    storage: '32Gb',
    chipset: 'Apple S8',
    batteryType: 'Li-Ion',
    material: 'aluminium',
    size: '41 x 35 x 10.7mm',
    weight: '42.3g',
  },
  {
    id: '23',
    name: 'Watch SE 2 44mm Starlight Aluminium White Sp/B',
    category: 'watches',
    brand: 'apple',
    release: '2022',
    bandColor: 'White',
    model: '(MNJX3UL/A)',
    price: '279',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-se-44/apple-watch-se-44-starlight-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-se-44/apple-watch-se-44-starlight-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-se-44/apple-watch-se-44-starlight-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-se-44/apple-watch-se-44-starlight-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/watches/apple/apple-watch-se-44/apple-watch-se-44-starlight-5.jpg',
    ],
    rating: 5,
    stock: 34,
    os: 'WatchOS',
    osVersion: '9.0',
    training: 'cycling, running, swimming',
    bodyShape: 'rectangle',
    control: 'buttons, touch screen',
    sensors:
      'accelerometer, gyro, heart rate, barometer, always-on altimeter, compass, SpO2',
    communication: 'GPS; Wi-Fi; Bluetooth',
    nfc: 'yes',
    protection: 'IP6X',
    resolution: '352 x 430',
    display: 'Retina',
    caseSize: '44mm',
    bluetooth: '5.0',
    storage: '32Gb',
    chipset: 'Apple S8',
    batteryType: 'Li-Ion',
    material: 'aluminium',
    size: '41 x 35 x 10.7mm',
    weight: '42.3g',
  },
  {
    id: '24',
    name: 'iPad Air 10.9” Wi-Fi',
    category: 'tablets',
    brand: 'apple',
    release: '2022',
    color: 'Purple',
    model: '(MME63)',
    price: '749',
    storage: '256Gb',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/tablets/apple/ipad-air-10.9-wi-fi/ipad-air-10.9-wi-fi-purple-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/tablets/apple/ipad-air-10.9-wi-fi/ipad-air-10.9-wi-fi-purple-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/tablets/apple/ipad-air-10.9-wi-fi/ipad-air-10.9-wi-fi-purple-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/tablets/apple/ipad-air-10.9-wi-fi/ipad-air-10.9-wi-fi-purple-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/tablets/apple/ipad-air-10.9-wi-fi/ipad-air-10.9-wi-fi-purple-5.jpg',
    ],
    rating: 4,
    stock: 78,
    displaySize: `10.9”`,
    display: 'Liquid Retina',
    resolution: '2360 x 1640',
    ppi: '264ppi',
    refreshRate: '60Hz',
    chipsetCores: '8',
    ram: '8Gb',
    communication: 'GPS; Wi-Fi; Bluetooth',
    features: 'dual camera; touch ID;',
    ports: 'USB Type-C',
    sdCardSupport: 'no',
    internet: 'no',
    numOfSIMs: 'no',
    typeOfSIM: 'no',
    chipset: 'Apple M1',
    cameras: '12MP + 12MP',
    maxVideoRecording: '1080p@60fps (front), 2160p@60fps (rear)',
    bluetooth: '5.0',
    os: 'iPadOS',
    osVersion: '16',
    protection: 'no',
    material: 'aluminum',
    size: '248.7 x 179.6 x 7.1mm',
    weight: '461g',
  },
  {
    id: '25',
    name: 'iPad Air 10.9” Wi-Fi + Cellular',
    category: 'tablets',
    brand: 'apple',
    release: '2022',
    color: 'Blue',
    model: '(MM6U3)',
    price: '749',
    storage: '64Gb',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/tablets/apple/ipad-air-10.9-wi-fi+cellular/ipad-air-10.9-wi-fi+cellular-blue-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/tablets/apple/ipad-air-10.9-wi-fi+cellular/ipad-air-10.9-wi-fi+cellular-blue-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/tablets/apple/ipad-air-10.9-wi-fi+cellular/ipad-air-10.9-wi-fi+cellular-blue-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/tablets/apple/ipad-air-10.9-wi-fi+cellular/ipad-air-10.9-wi-fi+cellular-blue-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/tablets/apple/ipad-air-10.9-wi-fi+cellular/ipad-air-10.9-wi-fi+cellular-blue-5.jpg',
    ],
    rating: 5,
    stock: 78,
    displaySize: `10.9”`,
    display: 'Liquid Retina',
    resolution: '2360 x 1640',
    ppi: '264ppi',
    refreshRate: '60Hz',
    chipsetCores: '8',
    ram: '8Gb',
    communication: 'GPS; Wi-Fi; Bluetooth',
    features: 'dual camera; touch ID;',
    ports: 'USB Type-C',
    sdCardSupport: 'no',
    internet: 'no',
    numOfSIMs: 'no',
    typeOfSIM: 'no',
    chipset: 'Apple M1',
    cameras: '12MP + 12MP',
    maxVideoRecording: '1080p@60fps (front), 2160p@60fps (rear)',
    bluetooth: '5.0',
    os: 'iPadOS',
    osVersion: '16',
    protection: 'no',
    material: 'aluminum',
    size: '248.7 x 179.6 x 7.1mm',
    weight: '461g',
  },
  {
    id: '26',
    name: 'iPad Pro 12.9” Wi-Fi',
    category: 'tablets',
    brand: 'apple',
    release: '2022',
    color: 'Silver',
    model: '(MNY03)',
    price: '2,199',
    storage: '2Tb',
    imgs: [
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/tablets/apple/ipad-pro-12.9-wi-fi/ipad-pro-12.9-wi-fi-silver-1.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/tablets/apple/ipad-pro-12.9-wi-fi/ipad-pro-12.9-wi-fi-silver-2.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/tablets/apple/ipad-pro-12.9-wi-fi/ipad-pro-12.9-wi-fi-silver-3.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/tablets/apple/ipad-pro-12.9-wi-fi/ipad-pro-12.9-wi-fi-silver-4.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/tablets/apple/ipad-pro-12.9-wi-fi/ipad-pro-12.9-wi-fi-silver-5.jpg',
      'https://raw.githubusercontent.com/kornienkokostia/online-store/develop/src/assets/images/tablets/apple/ipad-pro-12.9-wi-fi/ipad-pro-12.9-wi-fi-silver-6.jpg',
    ],
    rating: 5,
    stock: 143,
    displaySize: `12.9”`,
    display: 'Liquid Retina XDR',
    resolution: '2732 x 2048',
    ppi: '264ppi',
    refreshRate: '120Hz',
    chipsetCores: '8',
    ram: '8Gb',
    communication: 'GPS; Wi-Fi; Bluetooth',
    features: 'dual camera; face ID',
    ports: 'USB Type-C',
    sdCardSupport: 'no',
    chipset: 'Apple M2',
    cameras: '12MP + 10MP + 12MP',
    maxVideoRecording: '2160p@60fps',
    bluetooth: '5.3',
    os: 'iPadOS',
    osVersion: '16',
    protection: 'no',
    material: 'aluminum',
    size: '280.6 x 214.9 x 6.4mm',
    weight: '685g',
  }
];

export default productDB;
